# Generated by Django 5.0.1 on 2026-02-08 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text='e.g., CREATE, UPDATE, DELETE', max_length=50)),
                ('entity_type', models.CharField(db_index=True, help_text='e.g., Control, Evidence', max_length=50)),
                ('entity_id', models.CharField(db_index=True, help_text='ID of the entity', max_length=100)),
                ('before_json', models.JSONField(blank=True, help_text='State before change', null=True)),
                ('after_json', models.JSONField(blank=True, help_text='State after change', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__0bff9a_idx'), models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_58da28_idx')],
            },
        ),
    ]
