# Generated by Django 5.1.14 on 2026-02-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='controlevidencelink',
            new_name='evidence_co_control_cc08cf_idx',
            old_name='evidence_co_control_0d9b84_idx',
        ),
        migrations.RenameIndex(
            model_name='controlevidencelink',
            new_name='evidence_co_evidenc_a97ae0_idx',
            old_name='evidence_co_evidenc_8105d1_idx',
        ),
        migrations.RenameIndex(
            model_name='evidenceitem',
            new_name='evidence_ev_categor_836f41_idx',
            old_name='evidence_it_category_0c1574_idx',
        ),
    ]
