import io
from dataclasses import dataclass

from django.utils import timezone
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from apps.compliance.engine import compute_control_status, fetch_linked_evidence, recompute_and_persist
from apps.standards.models import Control, StandardPack


class NumberedFooterCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        page_count = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_footer(page_count)
            super().showPage()
        super().save()

    def draw_footer(self, page_count):
        self.setFont('Helvetica', 9)
        self.setFillColor(colors.grey)
        self.drawString(16 * mm, 10 * mm, 'Generated by AccrediVault')
        self.drawRightString(195 * mm, 10 * mm, f'Page {self._pageNumber} of {page_count}')


@dataclass
class ControlSnapshot:
    control: Control
    computed_status: str
    last_evidence_date: str | None
    next_due_date: str | None
    verification_state: str
    evidence_rows: list[list[str]]


def _safe_text(value):
    if value is None:
        return '-'
    return str(value)


def _table_style(header=False):
    style = [
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]
    if header:
        style.append(('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#ECEFF4')))
    else:
        style.append(('BACKGROUND', (0, 0), (0, -1), colors.whitesmoke))
    return TableStyle(style)


def _kpi_table_style():
    return TableStyle([
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#D6DCE5')),
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#334155')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 7),
        ('TOPPADDING', (0, 0), (-1, 0), 7),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 9),
        ('TOPPADDING', (0, 1), (-1, -1), 9),
    ])


def _status_fill(status_name: str):
    if status_name == 'OVERDUE':
        return colors.HexColor('#FEE2E2')
    if status_name == 'VERIFIED':
        return colors.HexColor('#D1FAE5')
    if status_name == 'READY':
        return colors.HexColor('#DCFCE7')
    if status_name == 'IN_PROGRESS':
        return colors.HexColor('#FEF3C7')
    return colors.HexColor('#F1F5F9')


def _verification_state_for(control: Control) -> str:
    latest = control.verifications.order_by('-verified_at').first()
    if latest is None:
        return 'NOT_VERIFIED'
    return latest.status


def build_control_snapshot(control: Control) -> ControlSnapshot:
    cache = getattr(control, 'status_cache', None)
    if cache is None:
        cache = recompute_and_persist(control)
    else:
        computed = compute_control_status(control)
        cache = recompute_and_persist(control, computed=computed)

    evidence_items = fetch_linked_evidence(control)
    evidence_rows = []
    for ev in evidence_items:
        evidence_rows.append([
            _safe_text(ev.title),
            _safe_text(ev.category),
            _safe_text(ev.event_date),
            _safe_text(ev.valid_until),
        ])

    return ControlSnapshot(
        control=control,
        computed_status=cache.computed_status,
        last_evidence_date=_safe_text(cache.last_evidence_date),
        next_due_date=_safe_text(cache.next_due_date),
        verification_state=_verification_state_for(control),
        evidence_rows=evidence_rows,
    )


def _add_cover_page(story, pack: StandardPack, title: str, styles):
    generated_at = timezone.now().strftime('%Y-%m-%d %H:%M:%S UTC')
    title_band = Table(
        [['ACCREDIVAULT COMPLIANCE EVIDENCE PACK']],
        colWidths=[165 * mm],
        rowHeights=[14 * mm],
    )
    title_band.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#1E293B')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 13),
    ]))
    story.append(title_band)
    story.append(Spacer(1, 10))
    story.append(Paragraph(title, ParagraphStyle('PackTitle', parent=styles['Heading2'], textColor=colors.HexColor('#0F172A'))))
    story.append(Spacer(1, 6))

    info = Table([
        ['Authority', _safe_text(pack.authority_code)],
        ['Pack Name', _safe_text(pack.name)],
        ['Pack Version', _safe_text(pack.version)],
        ['Generated At', generated_at],
    ], colWidths=[45 * mm, 120 * mm])
    info.setStyle(_table_style())
    story.append(info)
    story.append(Spacer(1, 10))

    kpi = Table(
        [
            ['CONTROLS', 'PACK STATUS', 'AUTHORITY'],
            [str(pack.controls.count()), _safe_text(pack.status).upper(), _safe_text(pack.authority_code)],
        ],
        colWidths=[55 * mm, 55 * mm, 55 * mm],
    )
    kpi.setStyle(_kpi_table_style())
    story.append(kpi)
    story.append(Spacer(1, 10))
    story.append(
        Paragraph(
            'This evidence pack is generated from the latest control snapshot and includes status, verification, '
            'and linked evidence details for audit use.',
            ParagraphStyle('CoverBody', parent=styles['BodyText'], fontSize=10, leading=14, textColor=colors.HexColor('#334155')),
        )
    )
    story.append(PageBreak())


def _add_section_summary_page(story, section_code: str, snapshots: list[ControlSnapshot], styles):
    story.append(Paragraph(f'Section Summary: {section_code}', ParagraphStyle('SectionTitle', parent=styles['Heading2'], textColor=colors.HexColor('#0F172A'))))
    story.append(Spacer(1, 6))

    in_progress = sum(1 for item in snapshots if item.computed_status == 'IN_PROGRESS')
    not_started = sum(1 for item in snapshots if item.computed_status == 'NOT_STARTED')
    ready = sum(1 for item in snapshots if item.computed_status == 'READY')
    verified = sum(1 for item in snapshots if item.computed_status == 'VERIFIED')
    overdue = sum(1 for item in snapshots if item.computed_status == 'OVERDUE')

    summary = Table(
        [
            ['TOTAL', 'NOT_STARTED', 'IN_PROGRESS', 'READY', 'VERIFIED', 'OVERDUE'],
            [len(snapshots), not_started, in_progress, ready, verified, overdue],
        ],
        colWidths=[27.5 * mm, 27.5 * mm, 27.5 * mm, 27.5 * mm, 27.5 * mm, 27.5 * mm],
    )
    summary.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#D6DCE5')),
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E293B')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8.5),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
        ('TOPPADDING', (0, 0), (-1, -1), 7),
        ('BACKGROUND', (3, 1), (3, 1), colors.HexColor('#DCFCE7')),
        ('BACKGROUND', (4, 1), (4, 1), colors.HexColor('#D1FAE5')),
        ('BACKGROUND', (5, 1), (5, 1), colors.HexColor('#FEE2E2')),
    ]))
    story.append(summary)
    story.append(Spacer(1, 10))
    story.append(
        Paragraph(
            'Use this section summary to quickly identify controls needing corrective action before inspection.',
            ParagraphStyle('SectionBody', parent=styles['BodyText'], fontSize=10, leading=14, textColor=colors.HexColor('#334155')),
        )
    )
    story.append(PageBreak())


def _add_control_pages(story, snapshots: list[ControlSnapshot], styles):
    for index, item in enumerate(snapshots):
        control = item.control
        story.append(Paragraph(f'Control: {_safe_text(control.control_code)}', ParagraphStyle('ControlTitle', parent=styles['Heading3'], textColor=colors.HexColor('#0F172A'))))
        story.append(Spacer(1, 4))

        details = Table([
            ['Control Code', _safe_text(control.control_code)],
            ['Indicator', _safe_text(control.indicator)],
            ['Status', _safe_text(item.computed_status)],
            ['Last Evidence Date', _safe_text(item.last_evidence_date)],
            ['Next Due Date', _safe_text(item.next_due_date)],
            ['Verification State', _safe_text(item.verification_state)],
        ], colWidths=[50 * mm, 115 * mm])
        details.setStyle(TableStyle([
            ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BACKGROUND', (0, 0), (0, -1), colors.whitesmoke),
            ('BACKGROUND', (1, 2), (1, 2), _status_fill(item.computed_status)),
        ]))
        story.append(details)
        story.append(Spacer(1, 6))

        story.append(Paragraph('Evidence List', ParagraphStyle('EvidenceTitle', parent=styles['Heading4'], textColor=colors.HexColor('#334155'))))
        if item.evidence_rows:
            rows = [['Title', 'Category', 'Event Date', 'Valid Until']] + item.evidence_rows
            evidence_tbl = Table(rows, colWidths=[68 * mm, 35 * mm, 30 * mm, 32 * mm])
            evidence_tbl.setStyle(TableStyle([
                ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#CBD5E1')),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 8.5),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
                ('TOPPADDING', (0, 0), (-1, 0), 6),
            ]))
            story.append(evidence_tbl)
        else:
            story.append(Paragraph('No evidence linked.', ParagraphStyle('NoEvidence', parent=styles['Normal'], textColor=colors.HexColor('#475569'))))

        if index < len(snapshots) - 1:
            story.append(PageBreak())


def generate_control_pdf_bytes(control: Control) -> bytes:
    return generate_controls_pdf_bytes(
        pack=control.standard_pack,
        controls=[control],
        title=f'Control Pack - {control.control_code}',
    )


def generate_controls_pdf_bytes(pack: StandardPack, controls: list[Control], title: str, section_code: str | None = None) -> bytes:
    styles = getSampleStyleSheet()
    snapshots = [build_control_snapshot(control) for control in controls]

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
    )

    story = []
    _add_cover_page(story, pack, title, styles)
    if section_code is not None:
        _add_section_summary_page(story, section_code, snapshots, styles)
    _add_control_pages(story, snapshots, styles)

    doc.build(story, canvasmaker=NumberedFooterCanvas)
    return buf.getvalue()
