# Generated by Django 5.0.1 on 2026-02-08 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_code', models.CharField(db_index=True, help_text='e.g., PHC', max_length=50)),
                ('name', models.CharField(help_text='e.g., PHC Lab Licensing Checklist', max_length=255)),
                ('version', models.CharField(help_text='e.g., 1.0', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('checksum', models.CharField(help_text='SHA256 of source file', max_length=64, unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source_file_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Standard Pack',
                'verbose_name_plural': 'Standard Packs',
                'ordering': ['-created_at'],
                'unique_together': {('authority_code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_code', models.CharField(db_index=True, help_text='e.g., PHC-ROM-001', max_length=50, unique=True)),
                ('section', models.CharField(db_index=True, help_text='Section name', max_length=255)),
                ('standard', models.TextField(help_text='Standard description')),
                ('indicator', models.TextField(help_text='Indicator/requirement text')),
                ('sort_order', models.IntegerField(db_index=True, default=0, help_text='Global sort order')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='standards.standardpack')),
            ],
            options={
                'verbose_name': 'Control',
                'verbose_name_plural': 'Controls',
                'ordering': ['sort_order'],
            },
        ),
    ]
