# Generated by Django 5.1.14 on 2026-02-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_code',
            field=models.CharField(db_index=True, help_text='e.g., PHC-ROM-001', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='control',
            unique_together={('standard_pack', 'control_code')},
        ),
    ]
