# Generated by Django 5.1.14 on 2026-02-11 11:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standards', '0002_alter_control_control_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlStatusCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_status', models.CharField(db_index=True, max_length=20)),
                ('last_evidence_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('control', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_cache', to='standards.control')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='standards.control')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('CONTROL', 'Control'), ('SECTION', 'Section')], db_index=True, max_length=20)),
                ('section_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('rule_type', models.CharField(choices=[('ONE_TIME', 'One Time'), ('FREQUENCY', 'Frequency'), ('ROLLING_WINDOW', 'Rolling Window'), ('EXPIRY', 'Expiry'), ('COUNT_IN_WINDOW', 'Count In Window')], max_length=30)),
                ('window_days', models.IntegerField(blank=True, null=True)),
                ('frequency_days', models.IntegerField(blank=True, null=True)),
                ('min_items', models.IntegerField(default=1)),
                ('requires_verification', models.BooleanField(default=False)),
                ('acceptable_categories', models.JSONField(blank=True, default=list)),
                ('acceptable_subtypes', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='standards.control')),
                ('standard_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_rules', to='standards.standardpack')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('CONTROL_PDF', 'Control PDF'), ('SECTION_PACK', 'Section Pack'), ('FULL_PACK', 'Full Pack')], max_length=30)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=20)),
                ('section_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('filters_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bucket', models.CharField(max_length=255)),
                ('object_key', models.CharField(max_length=1024, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='standards.control')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('standard_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='standards.standardpack')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
